env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - windows
  quotes:
    - error
    - single
    - avoidEscape: true
  jsx-quotes:
    - error
    - prefer-single
  react/prop-types:
    - warn
  semi:
    - error
    - always
